### ISSUE TITLE
大大你好呀。电报怎么在真机里跑，报这个错

### ISSUE THREAD

**Issue by leewaycn** [yingmu52/quan-ios#1]
![4fefe312871a6f5604e2ca13452b5e5e](https://user-images.githubusercontent.com/13659411/39357265-f2d73ba4-4a44-11e8-908a-fbe06b6fde53.jpg)

非常希望你能把流程写下来。模拟器是可以的。

**Comment by yingmu52** [comment]
@leewaycn 你好，你的问题提错项目了。不好意思。从截图上看，你需要开发者账号。

**Comment by leewaycn** [comment]
我也不想在这里提呀。你那pork 不能提issue
