### ISSUE TITLE
为啥我提的issues 被删了

### ISSUE THREAD

**Issue by leewaycn** [yingmu52/quan-ios#2]
为啥我提的issues 被删了为啥我提的issues 被删了为啥我提的issues 被删了为啥我提的issues 被删了

**Comment by yingmu52** [comment]
@leewaycn 不是被删了，是关了。我今天看了一下，貌似需要Telegram的developer account。所以真机上应该跑不了。

**Comment by leewaycn** [comment]
好的。跑好了。子工程也需要配置bundleiD 和开发者账号。
![149ce1b7e5098a5094d2e2660fc11811](https://user-images.githubusercontent.com/13659411/39391214-bbe65fa6-4ad2-11e8-96df-c3606685ae4b.jpg)

终于跑起来了。
